In [34]:
from array import * # array is a library which comes with muliple modules while installing the python.

In [35]:
arr = array ("i",[25,36,44])

In [36]:
print(arr)
print(type(arr))

array('i', [25, 36, 44])
<class 'array.array'>


In [37]:
print(dir(array))

['__add__', '__buffer__', '__class__', '__class_getitem__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__release_buffer__', '__repr__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'buffer_info', 'byteswap', 'count', 'extend', 'frombytes', 'fromfile', 'fromlist', 'fromunicode', 'index', 'insert', 'itemsize', 'pop', 'remove', 'reverse', 'tobytes', 'tofile', 'tolist', 'tounicode', 'typecode']


In [38]:
arr.append(99) # it works same as list, all the list functions are applicable on arrays:
print(arr)
arr.remove(99)
print(arr)
c=arr.count(99)
c

array('i', [25, 36, 44, 99])
array('i', [25, 36, 44])


0

In [39]:
import numpy as np  # need to import numpy before using arrays:

In [40]:
l=[1,2,3,4,5]

In [41]:
a=np.array(l) # this will conver the list into arrays:

In [42]:
print(a)

[1 2 3 4 5]


In [43]:
type(a)

numpy.ndarray

In [44]:
a.ndim # to find out the number of dimmensions:

1

In [45]:
b=np.array([8,9,10])
print(b)
print(type(b))

[ 8  9 10]
<class 'numpy.ndarray'>


#There are three types of arrays: 1-D,2-D,3-D

# 2D arrays

In [46]:
c=np.arange(1,21) # works same as range function to print the list of real numbers

In [47]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [48]:
d=c.reshape(4,5) #(rows,col): reshape to create the 1-D arrays to 2-D arrays: 

In [49]:
print(d)  
print(type(d))
print(d.ndim) # to know the dimension of the arrays:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
<class 'numpy.ndarray'>
2


In [50]:
d.shape # to know the shape of the arrays like rows,columns:

(4, 5)

In [51]:
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]
w=np.array([x,y,z]) # we can combine multiple lists and make a 2-d arrays: The same way to create the arrays from list:

In [52]:
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(w.shape)
print(w.ndim)

(3, 3)
2


In [54]:
j=np.arange(1,16).reshape(3,5)

In [55]:
print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [56]:
k=np.arange(16,31).reshape(5,3)

In [57]:
print(k)

[[16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [58]:
k.ndim

2

In [59]:
# Matrix muliplication: j(5*3)xk(3*5) (Column of first matrix X rows of second matrix) Both matrixes Column and rows should be equal:

In [60]:
j@k # use to multiply the j array to k array ((1*16)+(2*19)+(3*22)+(4*25)+(5*28)) for fist (1,1) row and col and so on for every other rows and col.

array([[ 360,  375,  390],
       [ 910,  950,  990],
       [1460, 1525, 1590]])

In [61]:
j.dot(k) # also can be cross muliply both the matrix with .dot():

array([[ 360,  375,  390],
       [ 910,  950,  990],
       [1460, 1525, 1590]])

# 3D arrays:

In [62]:
ts=np.arange(1,28).reshape(3,3,3)  # no of 2D arrays,rows, columns

In [63]:
print(ts)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [64]:
ts.ndim

3

In [65]:
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#Arithmetic Operation on Array

In [66]:
a+b 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [67]:
b-a

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [68]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [69]:
a/b

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [70]:
a//b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
a%b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b%a

C:\Users\Tarun\AppData\Local\Temp\ipykernel_2816\2686318045.py:1: RuntimeWarning: divide by zero encountered in remainder
  b%a


array([[0, 0, 0, 0],
       [0, 2, 0, 5],
       [4, 3, 2, 1]])

In [73]:
b//a

C:\Users\Tarun\AppData\Local\Temp\ipykernel_2816\997269450.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  b//a


array([[ 0, 13,  7,  5],
       [ 4,  3,  3,  2],
       [ 2,  2,  2,  2]])

In [74]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

#Predefine Arrays:

In [75]:
np.zeros(15).reshape(5,3) # bedfault it is in float can be changed to int,complex number:

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.zeros(15,dtype="int").reshape(5,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
np.zeros(15,dtype="complex").reshape(5,3)

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [78]:
np.ones(15).reshape(3,5) # to create an anrray of only ones value

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
np.eye(5) # returns a 2-D array with ones on the diagonal and zeros elsewhere (rows are compulsary,col are optional))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
g=np.eye(4,4)

In [81]:
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [82]:
np.max(a)

np.int64(11)

In [83]:
np.mean(a)

np.float64(5.5)

In [84]:
np.min(a)

np.int64(0)

In [85]:
np.random.random(15) # will create an array for random values between 0 to 1:reshaping the array is also possible:

array([0.59354111, 0.00562093, 0.03760682, 0.29612581, 0.13648803,
       0.97374445, 0.57835853, 0.93781144, 0.19326354, 0.11121936,
       0.2059704 , 0.37877543, 0.0346153 , 0.49874921, 0.44549126])

In [86]:
np.random.randint(1,25,50) # randint functino will return the random integer values between (1 to 25 and return 50 no values)

array([23, 18, 15,  3, 17,  5, 17, 23,  3, 20, 16, 15,  8,  2,  6, 21,  1,
       12, 22, 15,  6,  5, 19, 24,  2,  9, 15,  4, 15, 14,  1,  2, 23, 17,
       10, 22, 21, 22, 23, 12, 17,  9, 13, 19,  3, 20,  7, 20,  9, 19],
      dtype=int32)

In [87]:
np.random.normal(20,10,40) #will return the random values from 20 with fluctuation average of 10 values up and down and return total 40 values

array([28.39276139,  3.79899222, 14.67517959, 24.19079118, 10.68950113,
       36.5524383 , 10.94938677, 43.36824949, 16.29928593, 22.02134646,
       22.97256956, 26.46163597, 13.96382712, 22.75577199, 25.56692837,
        8.07770892, 18.14272709, 13.01706572, 29.92283755, 14.10809222,
       28.95166549, 34.29133786, 15.3842114 , 29.28520473, 15.25103084,
       28.71955426, 23.08088199, 11.8427391 , 18.78418246, 11.02083898,
       20.59684961, 27.25828044, 25.29777345, 34.3807306 , 12.15294185,
       23.13862535, 12.64963947, 12.0452052 , 26.32751857,  1.7023428 ])

In [88]:
np.linspace(1,2,50) # linspace is use to break the difference between numbers in no. of parts(Start from 1, end on 2, and wil return 50 float number) 

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [91]:
np.hstack(a) # will convert the normal into horizontal stock:

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
c=np.hstack(b)

In [105]:
print(c)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [106]:
np.vstack(c) # will conver the horizontal stack in to vertical stack

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [107]:
cc=np.random.randint(1,25,50)

In [108]:
cc

array([ 2, 17, 18, 20, 23, 17, 23,  3, 17,  4, 20, 19,  8,  3,  4, 22, 14,
        4, 14,  4, 24,  8, 22, 22, 13, 16,  1, 12,  1,  4, 16,  8, 11,  1,
        8, 23, 12, 13,  8,  6,  3, 17, 10, 19, 16,  1, 14,  4,  3,  4],
      dtype=int32)

In [112]:
np.unique(cc) #will give the unique values from the array

array([ 1,  2,  3,  4,  6,  8, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22,
       23, 24], dtype=int32)