In [240]:
import numpy as np

# 1. print 10 zeroes in array 
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [241]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2. print 10 Ones in array 
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [242]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 3. print 10 5 in array 
array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [245]:
np.random.randint(5,6,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

# 4. print the below ouput
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [21]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 5. create an array of even numbers in range of 10 to 50:
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [23]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 6. Create 3*3 martix ranging from 0 to 8:

In [25]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 7. Create 3*3 identity matrix:

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 8. use numpy to generate a random number between 0 to 1:

In [39]:
np.random.random(1)

array([0.79456879])

# 9. use numpy to generate an array of 25 random number sampled from standard normal dirstribution:

In [41]:
np.random.normal(0,1,25)

array([-0.06878646,  1.27976109, -1.07489233, -0.55869078, -0.23521009,
       -1.00536887, -0.34695646, -1.25642217,  1.67066078,  0.70069293,
        0.54137153, -1.20909034,  0.06039343, -0.92367581,  0.73426736,
       -0.31712572, -0.59841888, -1.64050436,  1.00640512,  1.281076  ,
       -0.41413909,  0.00659444, -0.23181391,  0.30740459,  0.63583655])

# 10: Create a matrix or an array of 100 between 0 to 1

In [246]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# 11.Create a matrix to print linearly spaced points between 0 to 1)

In [247]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [249]:
fe=np.arange(1,26).reshape(5,5)
print(fe)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Fetch the elements:

In [256]:
nfe=fe[2:5,1:5] # [select the rows star(2):to end(5),select the columns start(1):end(5)]
print(nfe)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [254]:
print(c[1,3])

9


In [91]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
d=np.arange(2,13,5)
np.vstack(d)

array([[ 2],
       [ 7],
       [12]])

#Fetch the rows from the array:

In [111]:
c=np.arange(1,26).reshape(5,5)

In [200]:
c[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#Use split function:

In [237]:
x = np.arange(10) 
np.array_split(x, 3) # array_split function will split the elements of an array into split value:split it into 3 parts:

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

#To find the sum of elements in the array

In [206]:
print(np.sum(c))

325


In [211]:
#Find the standard deviation of the array:

In [210]:
print(np.std(c))

7.211102550927978


In [219]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [234]:
# get the sum out of all the columns

In [235]:
np.sum(c,axis=0)

array([55, 60, 65, 70, 75])

numpy.ndarray